# Generated by Django 4.0.4 on 2022-05-29 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('aim', models.CharField(max_length=300)),
                ('sub_freq', models.IntegerField()),
                ('sub_tolerance', models.FloatField(default=0.1)),
                ('f_recipient', models.CharField(max_length=50)),
                ('end_date', models.DateField()),
                ('vote_deadline', models.DateField()),
                ('wager', models.IntegerField()),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refCont', to=settings.AUTH_USER_MODEL)),
                ('referee2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ref2Cont', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('notes', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('file', models.FileField(null=True, upload_to='')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.contract')),
            ],
        ),
    ]
